name: Dockerfile Lint

on: [pull_request]

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Hadolint
      run: |
        wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        chmod +x /bin/hadolint

    - name: Lint Dockerfile
      run: hadolint Dockerfile
